name: Sed-replacer
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "Mizuhararobot"
          replace: "Raya"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Welcome To Raya'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: TRTECHGUIDE
          commit_user_email: tharukrenujatechguide@gmail.com
          commit_author: TRTECHGUIDE <tharukrenujatechguide@gmail.com>
